# Generated by Django 3.2.12 on 2022-03-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('tracker_id', models.CharField(blank=True, max_length=32, null=True)),
                ('loc_x', models.IntegerField(blank=True, null=True)),
                ('loc_y', models.IntegerField(blank=True, null=True)),
                ('product_id', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(max_length=127, unique=True)),
                ('setting_value', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_id', models.CharField(max_length=127)),
            ],
        ),
    ]
